global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'eureka-server'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]
  - job_name: 'api-gateway'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8765' ]


#    eureka_sd_configs:
#      - server: http://host.docker.internal:8761/eureka
#      - source_labels: [ __address__ ]
#        regex: '.*'
#        target_label: instance
#        replacement: __param_target

