version: '3.7'

services:
  config-server:
    container_name: config-server
    image: config-server
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=default,native
    ports:
      - "8887:8888"
    networks:
      - network-msa-group-83

  eureka-server:
    container_name: eureka-server
    image: eureka-server
    restart: on-failure
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default,docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      config-server:
        condition: service_started
    networks:
      - network-msa-group-83

  ticket-service:
    container_name: ticket-service
    image: ticket-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=default,docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - network-msa-group-83

  tour-service:
    container_name: tour-service
    image: tour-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=default,docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - network-msa-group-83

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=default,docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      eureka-server:
        condition: service_started
    ports:
      - "8765:8765"
    networks:
      - network-msa-group-83

networks:
  network-msa-group-83: