spring:
  application:
    name: ticket-service

  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: "ticket-group-id"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

# settings for resilience4j is optional. works with default settings
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
    instances:
      findTourById:
        baseConfig: default
        waitDurationInOpenState: 20s

  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 100
        maxWaitDuration: 10ms
    instances:
      bulkheadFindTourById:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException


topic:
  send-tour: send-tour-event
